spring.application.name=Proyecto_POII_Ordenes

spring.datasource.url=jdbc:sqlserver://adventureworksserverpo2.database.windows.net:1433;databaseName=AdventureWorks;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=eduardo
spring.datasource.password=Edu98ardo
# server.port=8081
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true